<?php

// Auto generated by wpfluent Installer.

return array(
    'name' => 'FluentCommunity',
    'slug' => 'fluent-community',
    'domain_path' => '/language',
    'text_domain' => 'fluent-community',
    'hook_prefix' => 'fluent-community',
    'rest_namespace' => 'fluent-community',
    'rest_version' => 'v2',
    'env' => 'prod',
    'cipher' => 'AES-256-CBC',
    'key' => 'base64:4/VF9KA9s8xP4czFwFgf5/PkrJ/+AxsTjK/a8jEi9Uk=',
    //manifest start
     'manifest' => [
        'src/app.css' => array(
            'file' => 'app.css',
            'src' => 'src/app.css',
        ),
        'src/app.js' => array(
            'css' => array(
                'app.css',
            ),
            'file' => 'app.js',
            'isEntry' => true,
            'src' => 'src/app.js',
        ),
        'src/admin_app.css' => array(
            'file' => 'admin_app.css',
            'src' => 'src/admin_app.css',
        ),
        'src/admin_app.js' => array(
            'css' => array(
                'admin_app.css',
            ),
            'file' => 'admin_app.js',
            'isEntry' => true,
            'src' => 'src/admin_app.js',
        ),
        'src/customizer/customizer_app.css' => array(
            'file' => 'customizer_app.css',
            'src' => 'src/customizer/customizer_app.css',
        ),
        'src/customizer/customizer_app.js' => array(
            'css' => array(
                'customizer_app.css',
            ),
            'file' => 'customizer_app.js',
            'isEntry' => true,
            'src' => 'src/customizer/customizer_app.js',
        ),
        'src/Onboarding/onboarding.css' => array(
            'file' => 'onboarding.css',
            'src' => 'src/Onboarding/onboarding.css',
        ),
        'src/Onboarding/onboarding.js' => array(
            'css' => array(
                'onboarding.css',
            ),
            'file' => 'onboarding.js',
            'isEntry' => true,
            'src' => 'src/Onboarding/onboarding.js',
        ),
        'src/public/js/user_registration.css' => array(
            'file' => 'user_registration.css',
            'src' => 'src/public/js/user_registration.css',
        ),
        'src/public/js/user_registration.js' => array(
            'css' => array(
                'user_registration.css',
            ),
            'file' => 'user_registration.js',
            'isEntry' => true,
            'src' => 'src/public/js/user_registration.js',
        ),
        'src/global.scss' => array(
            'file' => 'global.css',
            'isEntry' => true,
            'src' => 'src/global.scss',
        ),
        'src/portal_general.js' => array(
            'file' => 'portal_general.js',
            'isEntry' => true,
            'src' => 'src/portal_general.js',
        ),
        'src/start.js' => array(
            'file' => 'start.js',
            'isEntry' => true,
            'src' => 'src/start.js',
        ),
        'src/theme-default.scss' => array(
            'file' => 'theme-default.css',
            'isEntry' => true,
            'src' => 'src/theme-default.scss',
        ),
    ]
    //manifest end
);
