<?php

namespace FluentCommunity\App\Services;

//This is a auto-generated file. Please do not modify
class AdminTransStrings
{
    public static function getStrings()
    {
        return [
            'Access & Features'                                                      => __('Access & Features', 'fluent-community'),
            'Advanced Features'                                                      => __('Advanced Features', 'fluent-community'),
            'Agencies'                                                               => __('Agencies', 'fluent-community'),
            'Almost done, just a few more seconds...'                                => __('Almost done, just a few more seconds...', 'fluent-community'),
            'Back'                                                                   => __('Back', 'fluent-community'),
            'Basic'                                                                  => __('Basic', 'fluent-community'),
            'Basic Settings of your portal'                                          => __('Basic Settings of your portal', 'fluent-community'),
            'Blank'                                                                  => __('Blank', 'fluent-community'),
            'Cancel'                                                                 => __('Cancel', 'fluent-community'),
            'Change'                                                                 => __('Change', 'fluent-community'),
            'Change Community URL'                                                   => __('Change Community URL', 'fluent-community'),
            'Change Logo'                                                            => __('Change Logo', 'fluent-community'),
            'Change Portal URL'                                                      => __('Change Portal URL', 'fluent-community'),
            'Click Here to Renew your License'                                       => __('Click Here to Renew your License', 'fluent-community'),
            'Click here'                                                             => __('Click here', 'fluent-community'),
            'Coaches'                                                                => __('Coaches', 'fluent-community'),
            'Community Name'                                                         => __('Community Name', 'fluent-community'),
            'Community Portal URL'                                                   => __('Community Portal URL', 'fluent-community'),
            'Continue to Next'                                                       => __('Continue to Next', 'fluent-community'),
            'Course'                                                                 => __('Course', 'fluent-community'),
            'Creators'                                                               => __('Creators', 'fluent-community'),
            'Currently set as publicly accessible.'                                  => __('Currently set as publicly accessible.', 'fluent-community'),
            'Currently set to: loggedin users can access'                            => __('Currently set to: loggedin users can access', 'fluent-community'),
            'Customization'                                                          => __('Customization', 'fluent-community'),
            'Customize the UI features of the portal.'                               => __('Customize the UI features of the portal.', 'fluent-community'),
            'Documentation'                                                          => __('Documentation', 'fluent-community'),
            'Educators'                                                              => __('Educators', 'fluent-community'),
            'Enter your new slug'                                                    => __('Enter your new slug', 'fluent-community'),
            'Everyone (public)'                                                      => __('Everyone (public)', 'fluent-community'),
            'Failed to change URL'                                                   => __('Failed to change URL', 'fluent-community'),
            'Fetching License Information Please wait.'                              => __('Fetching License Information Please wait.', 'fluent-community'),
            'Finishing up...'                                                        => __('Finishing up...', 'fluent-community'),
            'Get Feature Update via email'                                           => __('Get Feature Update via email', 'fluent-community'),
            'Go Back'                                                                => __('Go Back', 'fluent-community'),
            'Go to Permalink Settings'                                               => __('Go to Permalink Settings', 'fluent-community'),
            'Go to the portal'                                                       => __('Go to the portal', 'fluent-community'),
            'Have a new license Key?'                                                => __('Have a new license Key?', 'fluent-community'),
            'Integrated Marketing Automation'                                        => __('Integrated Marketing Automation', 'fluent-community'),
            'Join Official Community'                                                => __('Join Official Community', 'fluent-community'),
            'Just a moment please...'                                                => __('Just a moment please...', 'fluent-community'),
            'Learn More about FluentCommunity'                                       => __('Learn More about FluentCommunity', 'fluent-community'),
            'Let\'s build your community together!'                                  => __('Let\'s build your community together!', 'fluent-community'),
            'License Key'                                                            => __('License Key', 'fluent-community'),
            'License Management'                                                     => __('License Management', 'fluent-community'),
            'Logo'                                                                   => __('Logo', 'fluent-community'),
            'Looks like your community slug is already defined in wp-config.php'     => __('Looks like your community slug is already defined in wp-config.php', 'fluent-community'),
            'Looks like your license has expired.'                                   => __('Looks like your license has expired.', 'fluent-community'),
            'Manage Advanced Features and Addons'                                    => __('Manage Advanced Features and Addons', 'fluent-community'),
            'Manage Courses'                                                         => __('Manage Courses', 'fluent-community'),
            'Manage Your Plugin License'                                             => __('Manage Your Plugin License', 'fluent-community'),
            'Name your community'                                                    => __('Name your community', 'fluent-community'),
            'Non-Profits'                                                            => __('Non-Profits', 'fluent-community'),
            'Now you can access your community portal by clicking the button below.' => __('Now you can access your community portal by clicking the button below.', 'fluent-community'),
            'Only Logged In Users'                                                   => __('Only Logged In Users', 'fluent-community'),
            'Organizations'                                                          => __('Organizations', 'fluent-community'),
            'Pick a Fluent Community Template'                                       => __('Pick a Fluent Community Template', 'fluent-community'),
            'Please Provide a license key of'                                        => __('Please Provide a license key of', 'fluent-community'),
            'Please enter a valid slug'                                              => __('Please enter a valid slug', 'fluent-community'),
            'Please provide a license key'                                           => __('Please provide a license key', 'fluent-community'),
            'Please wait while we save your settings'                                => __('Please wait while we save your settings', 'fluent-community'),
            'Portal Settings'                                                        => __('Portal Settings', 'fluent-community'),
            'Portal Slug'                                                            => __('Portal Slug', 'fluent-community'),
            'Pretty Permalink is required'                                           => __('Pretty Permalink is required', 'fluent-community'),
            'Product'                                                                => __('Product', 'fluent-community'),
            'Purchase one here'                                                      => __('Purchase one here', 'fluent-community'),
            'Ready to make your community stand-out?'                                => __('Ready to make your community stand-out?', 'fluent-community'),
            'Recommended dimensions: 480 x 120, 4:1 aspect ratio'                    => __('Recommended dimensions: 480 x 120, 4:1 aspect ratio', 'fluent-community'),
            'Reliable Email delivery with FluentSMTP'                                => __('Reliable Email delivery with FluentSMTP', 'fluent-community'),
            'Monetize your Courses and Spaces with FluentCart'                       => __('Monetize your Courses and Spaces with FluentCart', 'fluent-community'),
            'Save & Finish'                                                          => __('Save & Finish', 'fluent-community'),
            'Settings saved successfully'                                            => __('Settings saved successfully', 'fluent-community'),
            'Setup who can access your portal & Setup Features'                      => __('Setup who can access your portal & Setup Features', 'fluent-community'),
            'Something is wrong! Please reload the page and try again.'              => __('Something is wrong! Please reload the page and try again.', 'fluent-community'),
            'Start your journey with our expertly crafted templates'                 => __('Start your journey with our expertly crafted templates', 'fluent-community'),
            'Subscribe to feature updates email newsletter'                          => __('Subscribe to feature updates email newsletter', 'fluent-community'),
            'The Blazing-Fast ⚡️ Community Solution for'                             => __('The Blazing-Fast ⚡️ Community Solution for', 'fluent-community'),
            'URL change canceled'                                                    => __('URL change canceled', 'fluent-community'),
            'Update this information anytime stress-free!'                           => __('Update this information anytime stress-free!', 'fluent-community'),
            'Upgrade to Pro'                                                         => __('Upgrade to Pro', 'fluent-community'),
            'Upload Logo'                                                            => __('Upload Logo', 'fluent-community'),
            'Verify License'                                                         => __('Verify License', 'fluent-community'),
            'View and Manage all of your courses'                                    => __('View and Manage all of your courses', 'fluent-community'),
            'Want to change the community URL?'                                      => __('Want to change the community URL?', 'fluent-community'),
            'Want to deactivate this license?'                                       => __('Want to deactivate this license?', 'fluent-community'),
            'We highly recommend to enable this feature.'                            => __('We highly recommend to enable this feature.', 'fluent-community'),
            'We highly recommend to enable this feature for monetization.'           => __('We highly recommend to enable this feature for monetization.', 'fluent-community'),
            'We recommend to install FluentSMTP.'                                    => __('We recommend to install FluentSMTP.', 'fluent-community'),
            'Who can access your portal'                                             => __('Who can access your portal', 'fluent-community'),
            'Yes, Change'                                                            => __('Yes, Change', 'fluent-community'),
            'Your Community is Ready 🚀'                                             => __('Your Community is Ready 🚀', 'fluent-community'),
            'Your Email Address'                                                     => __('Your Email Address', 'fluent-community'),
            'Your License Key'                                                       => __('Your License Key', 'fluent-community'),
            'Your Name'                                                              => __('Your Name', 'fluent-community'),
            'Your license key is valid and activated.'                               => __('Your license key is valid and activated.', 'fluent-community'),
            '__COMMUNITY_ACCESS_LABEL__'                                             => __('Select if your community can be accessed by public users or only logged in users.', 'fluent-community'),
            '__EMAIL_SUB_DESC__'                                                     => __('Subscribe to our newsletter to get feature updates, tips and tricks to grow your community. We promise not to spam you.', 'fluent-community'),
            '__FLUENT_CRM_DESC__'                                                    => __('Send targeted onboarding emails, marketing emails and run automations to your community members with FluentCRM.', 'fluent-community'),
            '__FLUENT_CART_DESC__'                                                   => __('Monetize your courses and spaces by creating and selling products directly in your community using FluentCart.', 'fluent-community'),
            '__IMPROVE_DESC__'                                                       => __('Help to improve the product by sharing non-sensitive data like members, spaces count.', 'fluent-community'),
            '__PERMALINK_CHANGE_DESC__'                                              => __('We do not recommend to change URL of your portal if you already have lots of contents. All of the portal related URLs will be changed by your new URL.', 'fluent-community'),
            '__permalink_broken_desk__'                                              => __('Looks like you did not set your permalink structure as pretty. FluentCommunity requires the permalink settings other than the plain.', 'fluent-community')
        ];
    }
}
